### ISSUE TITLE
Empty text fields are not sent to form handler

### ISSUE THREAD

**Issue by ckeeney** [ilxanlar/react-hooks-form#2]
If a text field has an empty string value, the form field is not sent to the `onSubmit` form handler.

**Comment by ilxanlar** [comment]
This is intentional. You can use `initialValues` for this:
```jsx
<Form initialValues={{ yourField: "" }}>
  ...
</Form>
```
This way, you make sure that `yourField` is passed to `onSubmit` function.

**Comment by ckeeney** [comment]
Thanks.
