### ISSUE TITLE
Incomplete index-based data on form submission

### ISSUE THREAD

**Issue by aldwyn** [ilxanlar/react-hooks-form#5]
Hi again @ilxanlar,

I have this issue on the form submission. I have created a snippet of my page that is enough to show you the issue.
```tsx
import React, { useState } from 'react';
import { Form, FormField } from 'react-hooks-form';

interface TimeSegment {
  start: string;
  end: string;
}

class AppointmentDay {
  name: string;
  time_segments: TimeSegment[] = [];

  constructor(name: string) {
    this.name = name;
  }
}

const SetAvailabilityPage = () => {
  const [apmtDayList, setApmtDayList] = useState([
    new AppointmentDay('Monday'),
    new AppointmentDay('Tuesday'),
    new AppointmentDay('Wednesday'),
    new AppointmentDay('Thursday'),
    new AppointmentDay('Friday'),
    new AppointmentDay('Saturday'),
    new AppointmentDay('Sunday'),
  ]);

  // 7 time_slots to represent the whole week
  const initialValues = {
    time_slots: [[], [], [], [], [], [], []],
  };

  const validate = (formValues: any) => {};

  const onSubmit = async (values: any) => {
    console.log(values);
  };

  const addTimeSegmentOnDay = (dayIndex: number) => {
    apmtDayList[dayIndex].time_segments.push({ start: '', end: '' });
    setApmtDayList([...apmtDayList]);
  };

  return (
    <div className="dashboard-content-outer">
      <div className="dashboard-content">
        <Form {...{ onSubmit, initialValues }}>
          {apmtDayList.map((item: AppointmentDay, i: number) => (
            <div key={`appointment_day-${i}`}>
              <h4>{item.name}</h4>
              <button className="btn" onClick={() => addTimeSegmentOnDay(i)}>Add Appointment</button>
              <div>
                {item.time_segments.map((ts: TimeSegment, j: number) => (
                  <div key={`time_slots-${i}-${j}`}>
                    Start:
                    <FormField component="input" type="text" name={`time_slots[${i}][${j}].start`} />
                    End:
                    <FormField component="input" type="text" name={`time_slots[${i}][${j}].end`} />
                  </div>
                ))}
              </div>
            </div>
          ))}
          <button>Submit</button>
        </Form>
      </div>
    </div>
  );
};
```

So when I click `Add Appointment`, it appends a new row (forgive the absence of CSS classes), and displays a new set of `start` and `end` input fields. When I try to add appointments on Monday and Thursday, only the value of Thursday is captured (or any `time_slots` input I edited the last). See console log from `onSubmit`.

Btw, Monday is `time_slots[0]` and Thursday is `time_slots[3]`.

<img width="400" alt="Screen Shot 2019-07-14 at 6 38 16 PM" src="https://user-images.githubusercontent.com/7032430/61182511-d1e79180-a666-11e9-9a4b-d7e5f031b76d.png">

Moreover, I tried doing the format `time_slots__${i}__${j}__start`/`time_slots__${i}__${j}__end` on the name to check if it has something with the indexing, but still, the last edited value is the only data being received on `onSubmit`. In this scenario, only `time_slots__3__0__start`/`time_slots__3__0__end` has values, and `time_slots__0__0__start`/`time_slots__0__0__end` don't.

**Comment by ilxanlar** [comment]
@aldwyn  Seems fine, it should work. Can you remove the validator completely and try again?

**Comment by aldwyn** [comment]
HI @ilxanlar, I have updated the startment on the `return` and made it work on my app, but still the issue persist. I removed the `validate` as suggested, but it didn't make a difference.

**Comment by ilxanlar** [comment]
@aldwyn  I built a component exactly like yours. There were no problems. Maybe something forces the form to unmount or something. I haven't figured it out yet. Any suggestions would help. Thanks.
